version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: gastr-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gastr_local
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data


